host: localhost
port: 11434
layout: panel
default_model: mistral:latest
documents_path: null

# Optional models for embedding faiss index
# Format is <model>:<dimension>
# NOTE: If you change this after creating an index
#       you will need to re-embed

# English only embedding models
embedding_model: msmarco-bert-base-dot-v5:768
# embedding_model: jinaai/jina-embeddings-v2-base-en:768
# embedding_model: BAAI/bge-large-en-v1.5:1024
# embedding_model: nomic-ai/nomic-embed-text-v1:768

# Multilingual embedding models
# embedding_model: intfloat/multilingual-e5-base:768
# embedding_model: BAAI/bge-m3:1024
